import { invalid } from "./errors.js";

export const MANUSCRIPT_DIR = "manuscript/";
export const GITLIT_DIR = ".gitlit/";
export const ARCHITECTURE_FILE = "manuscript_architecture.md";

/**
 * The trust-bearing subtrees of .gitlit/.
 *
 * These are the provenance record itself: the signed receipt chain, the public
 * keys that verify it, and the per-file span sidecars that say which text is
 * human and which is machine. They are GENERATED by the commit path (§5) from
 * what actually happened, and they are the entire evidentiary basis of the
 * product.
 *
 * Nothing a caller supplies — not an author's prose, not an agent's research,
 * not a request holding a valid service token — may write here. If a caller
 * could, it could sign its own receipts with a key it planted, or relabel
 * machine text as human, and offline verification would still say "valid":
 * the check trusts every key it finds and never re-derives the labels. The
 * only defence that holds is that these files can only be written by the code
 * that computes them. This is that defence.
 */
export const RESERVED_GITLIT_PREFIXES = [
  ".gitlit/receipts/",
  ".gitlit/keys/",
  ".gitlit/provenance/",
] as const;

export function isReservedPath(path: string): boolean {
  const p = normalizePath(path);
  return RESERVED_GITLIT_PREFIXES.some((prefix) => p.startsWith(prefix));
}

/**
 * A path any caller-supplied change must satisfy, enforced at the commit path
 * — the single place every write funnels through (§5), so no route can forget
 * it. Rejects the reserved subtrees above; everything else the route's own
 * allowlist governs.
 */
export function assertNotReserved(path: string): void {
  if (isReservedPath(path)) {
    throw invalid(
      `${normalizePath(path)} is generated by GitLit and cannot be written directly.`,
      { reject_reason: "reserved_path" },
    );
  }
}

/**
 * Paths an MCP agent may write (§8.3). Excludes manuscript/ — this is how "the
 * AI never writes prose" is enforced in code rather than policy — and excludes
 * the reserved provenance subtrees, so an agent:research token cannot forge a
 * receipt or plant a verifying key.
 */
export function assertAgentWritable(path: string): void {
  const p = normalizePath(path);
  const ok = (p === ARCHITECTURE_FILE || p.startsWith(GITLIT_DIR)) && !isReservedPath(p);
  if (!ok) {
    throw invalid(
      `Agents may write only ${ARCHITECTURE_FILE} and non-reserved ${GITLIT_DIR}** — refused "${p}".`,
      { reject_reason: "path_outside_allowlist" },
    );
  }
}

/**
 * Paths an AUTHOR may write through the documents route: prose, and the
 * top-level book metadata the editor manages. Never .gitlit/ — an author edits
 * their book, not the record of who wrote it.
 */
export function assertAuthorWritable(path: string): void {
  const p = normalizePath(path);
  const ok = (p.startsWith(MANUSCRIPT_DIR) || p === "book.yml" || p === ARCHITECTURE_FILE)
    && !p.startsWith(GITLIT_DIR);
  if (!ok) {
    throw invalid(
      `Authors may write ${MANUSCRIPT_DIR}**, book.yml and ${ARCHITECTURE_FILE} — refused "${p}".`,
      { reject_reason: "path_outside_allowlist" },
    );
  }
}

export function isProseFile(path: string): boolean {
  const p = normalizePath(path);
  return p.startsWith(MANUSCRIPT_DIR) && p.endsWith(".md");
}

/** Rejects traversal, absolute paths and backslashes before anything touches disk. */
export function normalizePath(path: string): string {
  const p = path.replace(/\\/g, "/").replace(/^\.\//, "");
  if (p.startsWith("/") || p.split("/").includes("..") || p.includes("\0")) {
    throw invalid(`Illegal path: "${path}"`, { reject_reason: "illegal_path" });
  }
  return p;
}
