import { describe, expect, it } from "vitest";
import {
  assertAgentWritable, assertAuthorWritable, assertNotReserved, isReservedPath,
} from "./paths.js";

/**
 * These guard the product's central claim. An author or agent who could write
 * into the reserved subtrees could sign forged receipts with a planted key or
 * relabel machine text as human, and offline verification would still say
 * "valid" — it trusts every key it finds and never re-derives the labels.
 *
 * Proven by exploit before this existed: all three writes returned 200 and a
 * clone verified as valid. Each case below is one of those writes.
 */
const RESERVED = [
  ".gitlit/keys/attacker.pub",
  ".gitlit/keys/nested/deep.pub",
  ".gitlit/receipts/chain.jsonl",
  ".gitlit/provenance/manuscript/chapters/01.md.jsonl",
];

const AGENT_LEGIT = [".gitlit/research/ledger.jsonl", ".gitlit/sessions/s1.json", "manuscript_architecture.md"];
const AUTHOR_LEGIT = ["manuscript/chapters/01.md", "book.yml", "manuscript_architecture.md"];

describe("reserved provenance paths", () => {
  it.each(RESERVED)("recognises %s as reserved", (p) => {
    expect(isReservedPath(p)).toBe(true);
  });

  it.each(RESERVED)("assertNotReserved rejects %s (the commit-path chokepoint)", (p) => {
    expect(() => assertNotReserved(p)).toThrow(/generated by GitLit/);
  });

  it("does not treat ordinary .gitlit files as reserved", () => {
    expect(isReservedPath(".gitlit/research/ledger.jsonl")).toBe(false);
    expect(isReservedPath(".gitlit/premise.md")).toBe(false);
  });

  it("is not fooled by a traversal that lands back in a reserved tree", () => {
    // normalizePath resolves .. first, so this either throws as illegal or
    // normalises into .gitlit/keys and is caught. Either way, not allowed.
    expect(() => assertNotReserved(".gitlit/research/../keys/x.pub")).toThrow();
  });
});

describe("an agent:research token cannot forge provenance", () => {
  it.each(RESERVED)("refuses %s", (p) => {
    expect(() => assertAgentWritable(p)).toThrow(/refused/);
  });
  it.each(AGENT_LEGIT)("still allows %s", (p) => {
    expect(() => assertAgentWritable(p)).not.toThrow();
  });
  it("still refuses prose, as before", () => {
    expect(() => assertAgentWritable("manuscript/chapters/01.md")).toThrow();
  });
});

describe("an author writes their book, not the record of who wrote it", () => {
  it.each(RESERVED)("refuses %s", (p) => {
    expect(() => assertAuthorWritable(p)).toThrow(/refused/);
  });
  it("refuses any .gitlit path, reserved or not", () => {
    expect(() => assertAuthorWritable(".gitlit/research/ledger.jsonl")).toThrow();
    expect(() => assertAuthorWritable(".gitlit/premise.md")).toThrow();
  });
  it.each(AUTHOR_LEGIT)("allows %s", (p) => {
    expect(() => assertAuthorWritable(p)).not.toThrow();
  });
});
